import { AIBehaviorType } from '../ai/types';

// --- Game Constants ---

export const GAME_SETTINGS = {
  TILE_SIZE: 100,
  DRAG_THRESHOLD: 3,
  ANIMATIONS: {
    ENABLED: false,
    MOVEMENT_DURATION: 200,
    ATTACK_DURATION: 400,
    SPELL_CAST_DURATION: 600,
    DAMAGE_DURATION: 800,
    HEAL_DURATION: 600,
    STATUS_EFFECT_DURATION: 500,
    DEATH_DURATION: 1000,
  },
} as const;

export const CREATURE_SIZES = {
  SMALL: 1,
  MEDIUM: 2,
  LARGE: 3,
  HUGE: 4,
} as const;

export const DIRECTIONS = {
  NORTH: 0,
  NORTHEAST: 1,
  EAST: 2,
  SOUTHEAST: 3,
  SOUTH: 4,
  SOUTHWEST: 5,
  WEST: 6,
  NORTHWEST: 7,
} as const;

export const DIRECTION_NAMES = {
  [DIRECTIONS.NORTH]: 'North',
  [DIRECTIONS.NORTHEAST]: 'Northeast',
  [DIRECTIONS.EAST]: 'East',
  [DIRECTIONS.SOUTHEAST]: 'Southeast',
  [DIRECTIONS.SOUTH]: 'South',
  [DIRECTIONS.SOUTHWEST]: 'Southwest',
  [DIRECTIONS.WEST]: 'West',
  [DIRECTIONS.NORTHWEST]: 'Northwest',
} as const;

export const DIRECTION_SHORT_NAMES = {
  [DIRECTIONS.NORTH]: 'N',
  [DIRECTIONS.NORTHEAST]: 'NE',
  [DIRECTIONS.EAST]: 'E',
  [DIRECTIONS.SOUTHEAST]: 'SE',
  [DIRECTIONS.SOUTH]: 'S',
  [DIRECTIONS.SOUTHWEST]: 'SW',
  [DIRECTIONS.WEST]: 'W',
  [DIRECTIONS.NORTHWEST]: 'NW',
} as const;

export const DIRECTION_ARROWS = {
  [DIRECTIONS.NORTH]: '↑',
  [DIRECTIONS.NORTHEAST]: '↗',
  [DIRECTIONS.EAST]: '→',
  [DIRECTIONS.SOUTHEAST]: '↘',
  [DIRECTIONS.SOUTH]: '↓',
  [DIRECTIONS.SOUTHWEST]: '↙',
  [DIRECTIONS.WEST]: '←',
  [DIRECTIONS.NORTHWEST]: '↖',
} as const;

export const COMBAT_CONSTANTS = {
  BACK_ATTACK_BONUS: 1,
  FLANKING_BONUS: 0.2,
  SHIELD_DEFENSE_BONUS: 1,
  AGILITY_TIEBREAKER_THRESHOLD: 0.1,
  HEALTH_RATIO_DENOMINATOR: 10,
  ARMOR_EFFECTIVENESS_MULTIPLIER: 0.5,
  VULNERABILITY_MULTIPLIER: 0.3,
  LIGHTING_PENALTY: -1, // Penalty for ranged attacks against targets in dimly lit or darker conditions
} as const;

export const MOVEMENT_CONSTANTS = {
  DIAGONAL_COST: 1.4,
  ENGAGED_MOVEMENT_LIMIT: 1,
  ZONE_OF_CONTROL_BLOCKING: true,
  CORNER_RULE_ENABLED: true,
} as const;
